arch:
- aarch64
- amd64
- armhf
- armv7
- i386
description: dnscrypt-proxy add-on for Home Assistant
init: false
map:
- addon_config:rw
name: dnsCrypt Proxy
ports:
  53/tcp: 53
  53/udp: 53
slug: dnscrypt-proxy
version: 2025.11.13
